### PR TITLE
feat: implement cursor blinking and xrdb keys for its params

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by actionless** [comment]
any problems with this one?

**Comment by neeasade** [comment]
this looks good. 

was holding off a bit until I merged upstream as well, will coordinate those today.

**Comment by neeasade** [comment]
yepp works great, thanks.

**Comment by actionless** [comment]
btw today i've just realized what this feature can be used to create a hack to emulate in terminal vim cursor change when mode changes (as in gvim)

**Comment by neeasade** [comment]
also had that in mind when I was taking a look -- ideally would match urxvt esc code for toggle?

**Comment by actionless** [comment]
what should i configure in xrdb and/or vim to reproduce that scenario?
or i should send those codes manually from vimL?

**Comment by neeasade** [comment]
the latter -- see http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes under "For VTE compatible terminals (urxvt, st, xterm, gnome-terminal 3.x and others)" 

I haven't tested to see if the existing listing already works.

**Comment by actionless** [comment]
cool, that works for me in urxvt, i'll try to add those escape codes to st when i'll have a minute

**Comment by neeasade** [comment]
already implemented -- just tested as well. 

https://github.com/neeasade/xst/blob/a32b4452762af7d744af711780277a6002617eec/src/st.c#L2602

**Comment by actionless** [comment]
for some reason with vimrc works with urxvt but not with the latest commit of xst:
```viml
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"
```

what cursor options do you have in config.h/xrdb now?

**Comment by neeasade** [comment]
https://u.teknik.io/S084e.webm

config.h matches the repo, xrdb in webm

**Comment by actionless** [comment]
for some reason my comment from the mail didn't got posted:

i did some more experiments and it came out what it's not working only inside tmux

**Comment by actionless** [comment]
i did some more experiments and it came out what it's not working only
inside tmux

**Comment by neeasade** [comment]
tmux has a 'wrapper' esc sequence, see http://vi.stackexchange.com/questions/3379/cursor-shape-under-vim-tmux for example.

**Comment by actionless** [comment]
thanks!
this worked for me:

```viml
if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>[6 q\<Esc>\\"
    let &t_SR = "\<Esc>Ptmux;\<Esc>\<Esc>[4 q\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>[2 q\<Esc>\\"
else
	let &t_SI = "\<Esc>[6 q"
	let &t_SR = "\<Esc>[4 q"
	let &t_EI = "\<Esc>[2 q"
endif
```

**Pull request merged**
