### PR TITLE
terminfo files are installed in DESTDIR

### PR DESCRIPTION
**Pull request by duganchen**

### CODE REVIEW

**Comment by neeasade** [comment]
LGTM, will merge this evening. This is also relevant to upstream.

http://git.suckless.org/st/tree/Makefile#n52

Thanks,
Nathan

**Comment by duganchen** [comment]
Would you be open to a pull request to add support for an
Xresources-configurable alpha transparency option?

That's something that would make xst more cool for me. I can leave the
default at "fully opaque" so that there's no change in behavior.

**Comment by neeasade** [comment]
I would be open to that -- we would propbably expose as 'xst.opacity'. Are you referring to the existing patch for it?

**Comment by duganchen** [comment]
I am. I'll get started soon.

**Pull request merged**
